projects:
  SalesLedgerApi-SalesLedgerApp-Backend-eu-west-1:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-west-1
        apiId: mglrg2nkw5dereoh7q3cyuv65m
        maxDepth: 2
extensions:
  amplify:
    version: 3
