# frontend/.graphqlconfig.yml
projects:
  codegen: # Or "Codegen Project" - your project name key
    schemaPath: "schema.graphql" # Ensure frontend/schema.graphql is your up-to-date schema
    includes:
      # Be very specific: point only to the directory where you MANUALLY created your .graphql operation files
      - "src/graphql/operations/**/*.graphql" 
    excludes:
      - ./amplify/**
      - "src/models/**"         # If you use DataStore
      - "src/aws-exports.js"    # If it exists
      - "src/graphql/API.ts"    # Exclude the output file itself
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: "src/graphql/API.ts" # All generated TS types AND operation documents here
        region: "eu-west-1"
        apiId: "mglrg2nkw5dereoh7q3cyuv65m" 
        frontend: typescript
        framework: react
        maxDepth: 3 
extensions:
  amplify:
    version: 3