projects:
  SalesLedgerAppFrontend:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        frontend: typescript
        framework: react
        maxDepth: 3
extensions:
  amplify:
    version: 3
