name: Deploy Backend and Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install

      - name: Deploy CDK backend and save outputs
        run: |
          cd backend
          npx cdk deploy --outputs-file ../cdk-outputs.json --require-approval never

      - name: Generate frontend .env from CDK outputs
        run: |
          node scripts/generate-env-from-cdk.js

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      
            - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Configure Amplify CLI
        run: |
          amplify configure project \
            --yes \
            --amplify "{\"envName\":\"prod\",\"defaultEditor\":\"code\"}" \
            --frontend "{\"frontend\":\"javascript\",\"framework\":\"react\",\"config\":{\"SourceDir\":\"frontend\",\"DistributionDir\":\"frontend/build\",\"BuildCommand\":\"npm run build\",\"StartCommand\":\"npm run start\"}}" \
            --providers "{\"awscloudformation\":{\"region\":\"${{ secrets.AWS_REGION }}\"}}"

      - name: Publish frontend to Amplify Console
        run: |
          cd frontend
          amplify publish --yes
 

